apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iooding-ingress
  namespace: iooding
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

    # Sticky session config
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "iooding_affinity"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "10800"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - iooding.local
      secretName: iooding-tls
  rules:
    - host: iooding.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iooding-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  ingressClassName: nginx
  rules:
    - host: longhorn.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
