apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: iooding-blog-pdb
  namespace: iooding
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: iooding-blog

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: iooding
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
