apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: iooding-critical
value: 1000000
globalDefault: false
description: "Used for core database pods to ensure they are the last to be evicted."
