apiVersion: v1
kind: ServiceAccount
metadata:
  name: iooding-sa
  namespace: iooding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iooding-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iooding-reader-binding
subjects:
- kind: ServiceAccount
  name: iooding-sa
  namespace: iooding
roleRef:
  kind: ClusterRole
  name: iooding-reader
  apiGroup: rbac.authorization.k8s.io
